// MOCK analyze() — hardcoded passport for development before Maaz's model lands.
import type { PassportResult } from "./types";

const EMBEDDING_DIM = Number(process.env.EMBEDDING_DIM ?? 512);

function seededEmbedding(seed: string, dim = EMBEDDING_DIM): number[] {
  let h = 1779033703 ^ seed.length;
  for (let i = 0; i < seed.length; i++) {
    h = Math.imul(h ^ seed.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  let a = h >>> 0;
  const rand = () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  const v = Array.from({ length: dim }, () => rand() * 2 - 1);
  const norm = Math.sqrt(v.reduce((s, x) => s + x * x, 0)) || 1;
  return v.map((x) => Number((x / norm).toFixed(6)));
}

export function mockAnalyze(imagePath: string): PassportResult {
  return {
    species: "dog",
    breed: "Golden Retriever",
    breed_confidence: 0.91,
    coat: {
      primary_color: "golden",
      secondary_color: "cream",
      pattern: "solid",
      distinctive_markings: "feathered tail, slight white blaze on chest",
    },
    triage: {
      severity: "moderate",
      severity_score: 2,
      observed_injuries: ["favoring front left paw", "matted fur on left flank"],
      urgent: false,
      triage_notes:
        "Alert and responsive. Mild limp on front left leg, likely a soft-tissue injury. Dehydration possible. Recommend vet examination within 2-3 hours.",
    },
    biometric: {
      embedding: seededEmbedding(imagePath || "mock"),
      embedding_model: "clip-ViT-B-32",
      embedding_dim: EMBEDDING_DIM,
    },
    photo_meta: {
      image_url: null,
      capture_timestamp: new Date().toISOString(),
    },
    raw_llm_response: "[mock] generated by lib/vision/mock.ts (golden retriever, moderate triage)",
  };
}
