// MOCK analyze() — hardcoded passport for development before Maaz's model lands.
import type { PassportResult } from "./types";
import { seededEmbedding } from "@/lib/embedding";

const EMBEDDING_DIM = Number(process.env.EMBEDDING_DIM ?? 512);

export function mockAnalyze(imagePath: string): PassportResult {
  return {
    species: "dog",
    breed: "Golden Retriever",
    breed_confidence: 0.91,
    coat: {
      primary_color: "golden",
      secondary_color: "cream",
      pattern: "solid",
      distinctive_markings: "feathered tail, slight white blaze on chest",
    },
    triage: {
      severity: "moderate",
      severity_score: 2,
      observed_injuries: ["favoring front left paw", "matted fur on left flank"],
      urgent: false,
      triage_notes:
        "Alert and responsive. Mild limp on front left leg, likely a soft-tissue injury. Dehydration possible. Recommend vet examination within 2-3 hours.",
    },
    biometric: {
      embedding: seededEmbedding(imagePath || "mock"),
      embedding_model: "clip-ViT-B-32",
      embedding_dim: EMBEDDING_DIM,
    },
    photo_meta: {
      image_url: null,
      capture_timestamp: new Date().toISOString(),
    },
    raw_llm_response: "[mock] generated by lib/vision/mock.ts (golden retriever, moderate triage)",
  };
}
